// <auto-generated />
using System;
using Ce.Gateway.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ce.Gateway.Api.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20251105153016_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Ce.Gateway.Api.Entities.RequestLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownstreamHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownstreamPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DownstreamPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownstreamQueryString")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DownstreamRequestSize")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DownstreamResponseSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownstreamScheme")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DownstreamStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long>("GatewayLatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsError")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamClientIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamHttpMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpstreamPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpstreamQueryString")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpstreamRequestSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpstreamScheme")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DownstreamHost");

                    b.HasIndex("UpstreamHost");

                    b.HasIndex("UpstreamPath");

                    b.HasIndex("CreatedAtUtc", "DownstreamStatusCode");

                    b.HasIndex("CreatedAtUtc", "IsError");

                    b.ToTable("OcrGatewayLogEntries");
                });

            modelBuilder.Entity("Ce.Gateway.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
