// <auto-generated />
using System;
using Ce.Gateway.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ce.Gateway.Api.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    partial class GatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Ce.Gateway.Api.Entities.RequestLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownstreamHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownstreamPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DownstreamPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownstreamQueryString")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DownstreamRequestSize")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DownstreamResponseSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownstreamScheme")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DownstreamStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long>("GatewayLatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsError")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamClientIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamHttpMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpstreamPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpstreamQueryString")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpstreamRequestSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpstreamScheme")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DownstreamHost");

                    b.ToTable("OcrGatewayLogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
